### ISSUE TITLE
create sublcass of EventDataset for running outside of ServiceX

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl_uproot#22]
Something like https://github.com/iris-hep/func_adl_xAOD/blob/3db3e594d4fe42f466ed9c1085ed21202600030d/func_adl_xAOD/backend/datasets/LocalFile.py#L38.

**Comment by gordonwatts** [comment]
As a warning, I'm planning on doing the same thing (again) for xAOD. I want to see if it is possible to re-use a bunch of the ServiceX_frontend stuff - so you would get caching, etc. You can see this work issue here: https://github.com/iris-hep/func_adl_xAOD/issues/55. I'm not going to tackle this, however, until I get the current frontned stuff done for version 1.0 of servicex (so it might take me a while).
